### ISSUE TITLE
請教NFC-Wifi-assistant範例

### ISSUE THREAD

**Issue by dearsherlock** [skyseraph/android_nfc_book#1]
請問NFC-Wifi-assistant範例中，是否必須自備NFC tag硬體才有辦法模擬資訊寫入tag這段情境？謝謝喔！
另外EasyTagWrite是否也是一樣需要？

**Comment by dearsherlock** [comment]
我若是需要兩隻NFC手機對碰後傳送資料，這樣的範例可以在哪裡找到呢？感謝！

**Comment by skyseraph** [comment]
@dearsherlock 
1. 需要Tag才能写入操作
2. 两台手机属于P2P模式，书中栗子中有讲述~
